# Generated by Django 3.1.2 on 2020-11-03 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarmentsManagementApp', '0002_auto_20201104_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garment',
            name='stock',
        ),
    ]
