# Generated by Django 3.1.2 on 2020-11-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarmentsManagementApp', '0004_auto_20201104_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
