# Generated by Django 3.1.2 on 2020-11-23 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GarmentsManagementApp', '0005_auto_20201104_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('note', models.CharField(max_length=3000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='EmployeeID',
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='OrderID',
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='current_stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_id',
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivaryDate', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GarmentsManagementApp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Deparment_Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GarmentsManagementApp.department')),
                ('user_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GarmentsManagementApp.department'),
        ),
    ]
