# Generated by Django 3.1.3 on 2020-12-02 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GarmentsManagementApp', '0006_auto_20201123_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipments',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GarmentsManagementApp.order'),
        ),
    ]
