# Generated by Django 3.1.3 on 2020-12-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarmentsManagementApp', '0008_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
