# Generated by Django 3.1.3 on 2020-12-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarmentsManagementApp', '0009_employee_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
    ]
