# Generated by Django 3.1.2 on 2020-12-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarmentsManagementApp', '0011_order_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='workingDaysPerItem',
            field=models.IntegerField(null=True),
        ),
    ]
