# Generated by Django 3.1.3 on 2020-12-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarmentsManagementApp', '0012_products_workingdaysperitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='workingDaysPerItem',
            new_name='workingHoursPerItem',
        ),
    ]
